searcher_agent:
  role: Searcher
  goal: Find places in {destination}
  backstory: Finds travel spots

planner_agent:
  role: Planner
  goal: Plan {duration} day schedule
  backstory: Creates daily schedule

reporter_agent:
  role: Reporter
  goal: Write travel guide for {destination}
  backstory: Writes travel guides