search_task:
  description: >
    Search for attractions, restaurants and activities in {destination}.
  expected_output: >
    List of attractions, restaurants and activities with details.
  agent: searcher_agent

plan_task:
  description: >
    Plan {duration}-day itinerary with travel times.
  expected_output: >
    Daily itinerary with travel routes and timing.
  agent: planner_agent
  context: [search_task]

report_task:
  description: >
    Generate travel report.
  expected_output: >
    Complete travel guide in markdown format.
  agent: reporter_agent
  context: [search_task, plan_task]
