find_and_plan_task:
  description: Find 3 attractions and 3 restaurants in {destination} and create {duration}-day schedule
  expected_output: "Day 1: 9AM [Attraction] → 12PM [Restaurant] → 2PM [Attraction]"
  agent: finder_agent

report_task:
  description: Write short travel guide under 100 words
  expected_output: Brief guide with daily schedule and place info
  agent: reporter_agent
  context: [find_and_plan_task]
